/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class DummyTest {
    @Test void dummyTest() {
        assertNotNull(new ArrayList<Integer>());
    }
}
